const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const PDFLib=require('../vendor/pdf-lib.min.js');
function profile(){const p=Buffer.alloc(132);p.writeUInt32BE(132);p.write('CMYK',16);p.write('acsp',36);return p;}
test('finishing keeps vector artwork at natural size and embeds exact profile',async()=>{const ctx={PDFLib,Uint8Array,DataView,Number,Error};vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/core.js','utf8'),ctx);const doc=await PDFLib.PDFDocument.create();doc.addPage([907,1276]).drawRectangle({x:12,y:34,width:100,height:50,color:PDFLib.cmyk(.1,.2,.3,.4)});const original=await doc.save();const output=await ctx.PrintCore.finish(original,profile(),320,450,'Test');const result=await PDFLib.PDFDocument.load(output);assert.equal(result.getPage(0).getWidth(),320*72/25.4);assert.equal(result.getPage(0).getHeight(),450*72/25.4);const intent=result.catalog.lookup(PDFLib.PDFName.of('OutputIntents'),PDFLib.PDFArray).lookup(0,PDFLib.PDFDict);const embedded=intent.lookup(PDFLib.PDFName.of('DestOutputProfile'),PDFLib.PDFRawStream);assert.equal(embedded.dict.lookup(PDFLib.PDFName.of('N'),PDFLib.PDFNumber).asNumber(),4);assert.deepEqual(Buffer.from(PDFLib.decodePDFRawStream(embedded).decode()),profile());const contents=result.getPage(0).node.Contents();const streams=contents.asArray().map(ref=>result.context.lookup(ref));const text=streams.map(s=>Buffer.from(PDFLib.decodePDFRawStream(s).decode()).toString()).join('\n');assert(text.includes('100'));assert(text.includes('50'));assert(text.includes('0.1 0.2 0.3 0.4 k'));assert(!text.includes(' rg'));});
function controller(nodes){const messages=[];const figma={showUI(){},on(){},currentPage:{selection:nodes},getNodeByIdAsync:async id=>nodes.find(n=>n.id===id),ui:{postMessage:m=>messages.push(m)}};const context={figma,__html__:'',Set};vm.createContext(context);vm.runInContext(fs.readFileSync('src/controller.js','utf8'),context);return {figma,messages};}
test('gradient preflight blocks export including text segment gradients',async()=>{let exports=0;const n={id:'1',type:'FRAME',parent:{},name:'Sheet',children:[{type:'TEXT',name:'Gradient text',characters:'a',getStyledTextSegments:()=>[{fills:[{type:'GRADIENT_LINEAR'}]}]}],exportAsync:async()=>{exports++;}};const {figma,messages}=controller([n]);await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(exports,0);assert.match(messages.at(-1).text,/Gradient/);});
test('selected frames export in supplied order without document writes',async()=>{const calls=[];const nodes=['2','1'].map(id=>Object.freeze({id,type:'FRAME',parent:{},name:id,width:907,height:1276,exportAsync:async options=>{assert.equal(options.format,'PDF');calls.push(id);return new Uint8Array([Number(id)]);}}));const {figma,messages}=controller(nodes);await figma.ui.onmessage({type:'export',ids:['1','2']});assert.deepEqual(calls,['1','2']);assert.equal(messages.at(-1).type,'pdfs');assert.equal(nodes[0].width,907);});
test('non-frame selection is rejected',async()=>{const {figma,messages}=controller([{id:'1',type:'GROUP',parent:{}}]);await figma.ui.onmessage({type:'export',ids:['1']});assert.match(messages.at(-1).text,/frames/);});
test('no-profile output removes inherited OutputIntent and retains CMYK vectors',async()=>{const ctx={PDFLib,Uint8Array,DataView,Number,Error};vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/core.js','utf8'),ctx);const doc=await PDFLib.PDFDocument.create();doc.addPage([907,1276]).drawRectangle({x:12,y:34,width:100,height:50,color:PDFLib.cmyk(.1,.2,.3,.4)});doc.catalog.set(PDFLib.PDFName.of('OutputIntents'),doc.context.obj([{Type:'OutputIntent'}]));const output=await ctx.PrintCore.finish(await doc.save(),null,320,450,'');const result=await PDFLib.PDFDocument.load(output);assert.equal(result.catalog.get(PDFLib.PDFName.of('OutputIntents')),undefined);assert.equal(result.getPage(0).getWidth(),320*72/25.4);const text=result.getPage(0).node.Contents().asArray().map(ref=>Buffer.from(PDFLib.decodePDFRawStream(result.context.lookup(ref)).decode()).toString()).join('\n');assert(text.includes('0.1 0.2 0.3 0.4 k'));});
test('automatic sizing gives differently sized frames their own PDF page dimensions',async()=>{const ctx={PDFLib,Uint8Array,DataView,Number,Error};vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/core.js','utf8'),ctx);const doc=await PDFLib.PDFDocument.create();doc.addPage([907,1276]);doc.addPage([595,842]);const output=await ctx.PrintCore.finish(await doc.save(),null,null,null,'',[{width:319.97,height:450.14},{width:209.9,height:297.04}]);const result=await PDFLib.PDFDocument.load(output);assert.equal(result.getPage(0).getWidth(),319.97*72/25.4);assert.equal(result.getPage(1).getWidth(),209.9*72/25.4);assert.equal(result.getPage(1).getHeight(),297.04*72/25.4);});
test('concurrent profile imports are serialized so neither is lost',async()=>{const {figma,messages}=controller([]);let stored;figma.clientStorage={getAsync:async()=>stored?JSON.parse(JSON.stringify(stored)):undefined,setAsync:async(key,value)=>{await new Promise(resolve=>setTimeout(resolve,2));stored=JSON.parse(JSON.stringify(value));}};await Promise.all([figma.ui.onmessage({type:'save-profile',id:'one',encoded:'abc'}),figma.ui.onmessage({type:'save-profile',id:'two',encoded:'def'})]);assert.deepEqual(stored,{one:'abc',two:'def'});await figma.ui.onmessage({type:'load-profiles'});assert.deepEqual(messages.at(-1).profiles,stored);});
test('storage failure leaves conversion available and reports session-only import',async()=>{const {figma,messages}=controller([]);figma.clientStorage={getAsync:async()=>({}),setAsync:async()=>{throw new Error('Quota exceeded');}};await figma.ui.onmessage({type:'save-profile',id:'one',encoded:'abc'});assert.equal(messages.at(-1).type,'profile-storage-error');});
test('preflight issues name their frame and layer',async()=>{const n={id:'1',type:'FRAME',parent:{},name:'Sheet',children:[{id:'5',type:'RECTANGLE',name:'Shadowed',effects:[{type:'DROP_SHADOW'}]}],exportAsync:async()=>{}};const {figma,messages}=controller([n]);await figma.ui.onmessage({type:'export',ids:['1']});assert.deepEqual(JSON.parse(JSON.stringify(messages.at(-1).issues)),[{kind:'effect',text:'Effect in Shadowed (may rasterize)',frameId:'1',nodeId:'5',name:'Shadowed'}]);});
test('cancel stops a running export before it posts PDFs',async()=>{let release;const nodes=['1','2'].map(id=>({id,type:'FRAME',parent:{},name:id,width:10,height:10,exportAsync:()=>new Promise(resolve=>{release=()=>resolve(new Uint8Array([1]));})}));const {figma,messages}=controller(nodes);const running=figma.ui.onmessage({type:'export',ids:['1','2']});await new Promise(r=>setImmediate(r));await figma.ui.onmessage({type:'cancel'});release();await running;assert(!messages.some(m=>m.type==='pdfs'));assert.equal(messages.filter(m=>m.type==='status').length,1);});
test('show-layer zooms to the layer without selecting it',async()=>{const layer={id:'5',type:'RECTANGLE'};const {figma}=controller([]);let shown;figma.getNodeByIdAsync=async id=>id==='5'?layer:null;figma.viewport={scrollAndZoomIntoView:nodes=>shown=nodes};await figma.ui.onmessage({type:'show-layer',id:'5'});assert.equal(shown.length,1);assert.equal(shown[0],layer);assert.deepEqual(figma.currentPage.selection,[]);});
