const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const PDFLib=require('../vendor/pdf-lib.min.js');
function profile(){const p=Buffer.alloc(132);p.writeUInt32BE(132);p.write('CMYK',16);p.write('acsp',36);return p;}
test('finishing keeps vector artwork at natural size and embeds exact profile',async()=>{const ctx={PDFLib,Uint8Array,DataView,Number,Error};vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/core.js','utf8'),ctx);const doc=await PDFLib.PDFDocument.create();doc.addPage([907,1276]).drawRectangle({x:12,y:34,width:100,height:50,color:PDFLib.cmyk(.1,.2,.3,.4)});const original=await doc.save();const output=await ctx.PrintCore.finish(original,profile(),320,450,'Test');const result=await PDFLib.PDFDocument.load(output);assert.equal(result.getPage(0).getWidth(),320*72/25.4);assert.equal(result.getPage(0).getHeight(),450*72/25.4);const intent=result.catalog.lookup(PDFLib.PDFName.of('OutputIntents'),PDFLib.PDFArray).lookup(0,PDFLib.PDFDict);const embedded=intent.lookup(PDFLib.PDFName.of('DestOutputProfile'),PDFLib.PDFRawStream);assert.equal(embedded.dict.lookup(PDFLib.PDFName.of('N'),PDFLib.PDFNumber).asNumber(),4);assert.deepEqual(Buffer.from(PDFLib.decodePDFRawStream(embedded).decode()),profile());const contents=result.getPage(0).node.Contents();const streams=contents.asArray().map(ref=>result.context.lookup(ref));const text=streams.map(s=>Buffer.from(PDFLib.decodePDFRawStream(s).decode()).toString()).join('\n');assert(text.includes('100'));assert(text.includes('50'));assert(text.includes('0.1 0.2 0.3 0.4 k'));assert(!text.includes(' rg'));});
function controller(nodes){const messages=[];const figma={showUI(){},on(){},currentPage:{selection:nodes},getNodeByIdAsync:async id=>nodes.find(n=>n.id===id),ui:{postMessage:m=>messages.push(m)}};const context={figma,__html__:'',Set};vm.createContext(context);vm.runInContext(fs.readFileSync('src/controller.js','utf8'),context);return {figma,messages};}
test('gradients no longer block export, including text segment gradients',async()=>{let exports=0;const n={id:'1',type:'FRAME',parent:{},name:'Sheet',width:200,height:100,fills:[{type:'GRADIENT_ANGULAR'}],children:[{type:'TEXT',name:'Gradient text',characters:'a',getStyledTextSegments:()=>[{fills:[{type:'GRADIENT_LINEAR'}]}]}],exportAsync:async()=>{exports++;return new Uint8Array([1]);}};const {figma,messages}=controller([n]);await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(exports,1);assert.equal(messages.at(-1).type,'pdfs');assert.deepEqual([...messages.at(-1).scales],[1]);});
function effectFrame(effects,size={width:200,height:100},cloneFails=false){
 const log={original:0,copy:[],appended:0};
 const frame=Object.freeze({id:'1',type:'FRAME',parent:{},name:'Card',...size,children:[Object.freeze({type:'RECTANGLE',name:'Shadowed',effects})],
  exportAsync:async()=>{log.original++;return new Uint8Array([1]);},
  clone:()=>{if(cloneFails)throw new Error('View-only file');const copy={removed:false,rescale:k=>log.copy.push(['rescale',k]),exportAsync:async o=>{log.copy.push(['export',o.format]);return new Uint8Array([2]);},remove(){log.copy.push(['remove']);this.removed=true;}};return copy;}});
 return {frame,log};
}
function effectController(frame,log){const c=controller([frame]);c.figma.currentPage.appendChild=()=>log.appended++;return c;}
test('frames with effects export from a removed, scaled copy at 300 ppi and leave the original untouched',async()=>{
 const {frame,log}=effectFrame([{type:'DROP_SHADOW',visible:true},{type:'BACKGROUND_BLUR',visible:true}]);const {figma,messages}=effectController(frame,log);
 await figma.ui.onmessage({type:'export',ids:['1']});const msg=messages.at(-1);
 assert.equal(msg.type,'pdfs');assert.equal(log.original,0);assert.equal(log.appended,1);
 assert.deepEqual(log.copy.map(c=>c[0]),['rescale','export','remove']);assert(log.copy[0][1]*144>=300,'scale reaches 300 ppi');
 assert.equal(msg.scales[0],log.copy[0][1]);assert(msg.effectPpi>=300);assert.equal(frame.width,200);
});
test('hidden effects do not trigger the scaled export',async()=>{const {frame,log}=effectFrame([{type:'DROP_SHADOW',visible:false}]);const {figma,messages}=effectController(frame,log);await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(log.original,1);assert.deepEqual(log.copy,[]);assert.equal(messages.at(-1).effectPpi,null);});
test('unsupported effect types still block export',async()=>{const {frame,log}=effectFrame([{type:'GLASS',visible:true}]);const {figma,messages}=effectController(frame,log);await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(messages.at(-1).type,'error');assert.match(messages.at(-1).text,/Unsupported effect in Shadowed/);assert.equal(log.original,0);});
test('when a copy cannot be made, effects fall back to Figma’s 144 ppi and say so',async()=>{const {frame,log}=effectFrame([{type:'LAYER_BLUR',visible:true}],undefined,true);const {figma,messages}=effectController(frame,log);await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(log.original,1);assert.equal(messages.at(-1).scales[0],1);assert.equal(messages.at(-1).effectPpi,144);});
test('very large effect frames cap the scale so bitmaps stay within limits',async()=>{const {frame,log}=effectFrame([{type:'INNER_SHADOW',visible:true}],{width:5669,height:4000});const {figma,messages}=effectController(frame,log);await figma.ui.onmessage({type:'export',ids:['1']});const k=log.copy[0][1];assert(k<2&&k*2*5669<=16384+1e-6);assert.equal(messages.at(-1).effectPpi,Math.round(144*k));});
test('selected frames export in supplied order without document writes',async()=>{const calls=[];const nodes=['2','1'].map(id=>Object.freeze({id,type:'FRAME',parent:{},name:id,width:907,height:1276,exportAsync:async options=>{assert.equal(options.format,'PDF');calls.push(id);return new Uint8Array([Number(id)]);}}));const {figma,messages}=controller(nodes);await figma.ui.onmessage({type:'export',ids:['1','2']});assert.deepEqual(calls,['1','2']);assert.equal(messages.at(-1).type,'pdfs');assert.equal(nodes[0].width,907);});
test('non-frame selection is rejected',async()=>{const {figma,messages}=controller([{id:'1',type:'GROUP',parent:{}}]);await figma.ui.onmessage({type:'export',ids:['1']});assert.match(messages.at(-1).text,/frames/);});
test('no-profile output removes inherited OutputIntent and retains CMYK vectors',async()=>{const ctx={PDFLib,Uint8Array,DataView,Number,Error};vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/core.js','utf8'),ctx);const doc=await PDFLib.PDFDocument.create();doc.addPage([907,1276]).drawRectangle({x:12,y:34,width:100,height:50,color:PDFLib.cmyk(.1,.2,.3,.4)});doc.catalog.set(PDFLib.PDFName.of('OutputIntents'),doc.context.obj([{Type:'OutputIntent'}]));const output=await ctx.PrintCore.finish(await doc.save(),null,320,450,'');const result=await PDFLib.PDFDocument.load(output);assert.equal(result.catalog.get(PDFLib.PDFName.of('OutputIntents')),undefined);assert.equal(result.getPage(0).getWidth(),320*72/25.4);const text=result.getPage(0).node.Contents().asArray().map(ref=>Buffer.from(PDFLib.decodePDFRawStream(result.context.lookup(ref)).decode()).toString()).join('\n');assert(text.includes('0.1 0.2 0.3 0.4 k'));});
test('automatic sizing gives differently sized frames their own PDF page dimensions',async()=>{const ctx={PDFLib,Uint8Array,DataView,Number,Error};vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/core.js','utf8'),ctx);const doc=await PDFLib.PDFDocument.create();doc.addPage([907,1276]);doc.addPage([595,842]);const output=await ctx.PrintCore.finish(await doc.save(),null,null,null,'',[{width:319.97,height:450.14},{width:209.9,height:297.04}]);const result=await PDFLib.PDFDocument.load(output);assert.equal(result.getPage(0).getWidth(),319.97*72/25.4);assert.equal(result.getPage(1).getWidth(),209.9*72/25.4);assert.equal(result.getPage(1).getHeight(),297.04*72/25.4);});
test('concurrent profile imports are serialized so neither is lost',async()=>{const {figma,messages}=controller([]);let stored;figma.clientStorage={getAsync:async()=>stored?JSON.parse(JSON.stringify(stored)):undefined,setAsync:async(key,value)=>{await new Promise(resolve=>setTimeout(resolve,2));stored=JSON.parse(JSON.stringify(value));}};await Promise.all([figma.ui.onmessage({type:'save-profile',id:'one',encoded:'abc'}),figma.ui.onmessage({type:'save-profile',id:'two',encoded:'def'})]);assert.deepEqual(stored,{one:'abc',two:'def'});await figma.ui.onmessage({type:'load-profiles'});assert.deepEqual(messages.at(-1).profiles,stored);});
test('storage failure leaves conversion available and reports session-only import',async()=>{const {figma,messages}=controller([]);figma.clientStorage={getAsync:async()=>({}),setAsync:async()=>{throw new Error('Quota exceeded');}};await figma.ui.onmessage({type:'save-profile',id:'one',encoded:'abc'});assert.equal(messages.at(-1).type,'profile-storage-error');});
test('preflight issues name their frame and layer',async()=>{const n={id:'1',type:'FRAME',parent:{},name:'Sheet',children:[{id:'5',type:'RECTANGLE',name:'Shadowed',effects:[{type:'GLASS'}]}],exportAsync:async()=>{}};const {figma,messages}=controller([n]);await figma.ui.onmessage({type:'export',ids:['1']});assert.deepEqual(JSON.parse(JSON.stringify(messages.at(-1).issues)),[{kind:'effect',text:'Unsupported effect in Shadowed',frameId:'1',nodeId:'5',name:'Shadowed'}]);});
test('cancel stops a running export before it posts PDFs',async()=>{let release;const nodes=['1','2'].map(id=>({id,type:'FRAME',parent:{},name:id,width:10,height:10,exportAsync:()=>new Promise(resolve=>{release=()=>resolve(new Uint8Array([1]));})}));const {figma,messages}=controller(nodes);const running=figma.ui.onmessage({type:'export',ids:['1','2']});await new Promise(r=>setImmediate(r));await figma.ui.onmessage({type:'cancel'});release();await running;assert(!messages.some(m=>m.type==='pdfs'));assert.equal(messages.filter(m=>m.type==='status').length,1);});
test('show-layer zooms to the layer without selecting it',async()=>{const layer={id:'5',type:'RECTANGLE'};const {figma}=controller([]);let shown;figma.getNodeByIdAsync=async id=>id==='5'?layer:null;figma.viewport={scrollAndZoomIntoView:nodes=>shown=nodes};await figma.ui.onmessage({type:'show-layer',id:'5'});assert.equal(shown.length,1);assert.equal(shown[0],layer);assert.deepEqual(figma.currentPage.selection,[]);});
// A small node tree for the noise and texture tests. Copies live 2x larger so the test can tell original and copy bounds apart.
function rasterTree({frameEffects=[],childEffects=[{type:'NOISE',visible:true}],childType='RECTANGLE',inInstance=false,size=100,cloneFails=false}={}){
 const log={pngs:[],images:0,detached:0,inserted:[]};
 const box=(x,y,w,h)=>({x,y,width:w,height:h});
 function node(props,k){const n={visible:true,effects:[],opacity:1,blendMode:'NORMAL',relativeTransform:[[1,0,10*k],[0,1,10*k]],absoluteTransform:[[1,0,10*k],[0,1,10*k]],...props};if(n.children)for(const c of n.children)c.parent=n;n.insertChild=(i,c)=>{n.children.splice(i,0,c);c.parent=n;log.inserted.push(c);};n.remove=()=>{const s=n.parent.children;s.splice(s.indexOf(n),1);};return n;}
 function tree(k){
  const leaf=node({id:'5',type:childType,name:'Grain',effects:childEffects,absoluteRenderBounds:box(10*k,10*k,size*k,size*k),absoluteBoundingBox:box(10*k,10*k,size*k,size*k),exportAsync:async o=>{log.pngs.push({who:k,...o});return new Uint8Array([3]);}},k);
  const above=node({id:'6',type:'TEXT',name:'Title'},k);
  let holder=node({id:'4',type:inInstance?'INSTANCE':'FRAME',name:'Card',children:[leaf,above],layoutMode:'VERTICAL'},k);
  if(inInstance)holder.detachInstance=()=>{log.detached++;holder.type='FRAME';return holder;};
  return node({id:'1',type:'FRAME',parent:{},name:'Poster',width:200,height:100,effects:frameEffects,fills:[],strokes:[],children:[holder],absoluteBoundingBox:box(0,0,200*k,100*k),absoluteRenderBounds:box(0,0,200*k,100*k),exportAsync:async o=>{log.pngs.push({who:k,...o});return new Uint8Array([o.format==='PDF'?1:3]);}},k);
 }
 const frame=tree(1);
 frame.clone=()=>{if(cloneFails)throw new Error('View-only file');const copy=tree(2);log.copy=copy;copy.rescale=()=>{};copy.exportAsync=async o=>{log.copyPdf=o.format;return new Uint8Array([2]);};copy.remove=()=>{copy.removed=true;};return copy;};
 const c=controller([frame]);c.figma.currentPage.appendChild=()=>{};c.figma.createImage=()=>({hash:'img'+(++log.images)});
 c.figma.createRectangle=()=>({type:'RECTANGLE',resize(w,h){this.size=[w,h];}});
 return {frame,log,...c};
}
test('noise and texture layers are swapped for a 300 ppi image in the copy, above the hidden layer and keeping its place',async()=>{
 for(const type of ['NOISE','TEXTURE']){
  const {frame,log,figma,messages}=rasterTree({childEffects:[{type,visible:true},{type:'DROP_SHADOW',visible:true}]});
  await figma.ui.onmessage({type:'export',ids:['1']});const msg=messages.at(-1);
  assert.equal(msg.type,'pdfs',msg.text);assert.equal(msg.effectPpi,300);assert.equal(log.copyPdf,'PDF');assert(log.copy.removed);
  assert.equal(log.pngs.length,1);assert.equal(log.pngs[0].who,1,'PNG comes from the original');assert.equal(log.pngs[0].format,'PNG');assert.equal(log.pngs[0].constraint.value,300/72);
  const card=log.copy.children[0];assert.deepEqual(card.children.map(c=>c.name),['Grain','Grain','Title']);
  const image=card.children[1];assert.equal(image.fills[0].imageHash,'img1');assert.equal(image.layoutPositioning,'ABSOLUTE');assert.deepEqual(image.size,[200,200]);
  assert.deepEqual(JSON.parse(JSON.stringify(image.relativeTransform)),[[1,0,20],[0,1,20]]);assert.equal(card.children[0].opacity,0);
  assert.equal(frame.children[0].children.length,2);assert.equal(frame.children[0].children[0].opacity,1);
 }
});
test('noise inside a component instance detaches the instance in the copy only',async()=>{const {frame,log,figma,messages}=rasterTree({inInstance:true});await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(messages.at(-1).type,'pdfs');assert.equal(log.detached,1);assert.equal(frame.children[0].type,'INSTANCE');assert.equal(log.copy.children[0].children.length,3);});
test('noise on the frame itself turns the copied page into one image at frame size',async()=>{const {log,figma,messages}=rasterTree({frameEffects:[{type:'NOISE',visible:true}]});await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(messages.at(-1).type,'pdfs',messages.at(-1).text);assert.equal(log.pngs[0].useAbsoluteBounds,true);assert.deepEqual(log.copy.children,[]);assert.equal(log.copy.fills[0].type,'IMAGE');});
test('layers too big for a 4096 px image report the lower ppi',async()=>{const {log,figma,messages}=rasterTree({size:2000});await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(log.pngs[0].constraint.value,4096/2000);assert.equal(messages.at(-1).effectPpi,Math.round(72*4096/2000));});
test('hidden noise is ignored and unsupported effects inside a rasterised layer do not block export',async()=>{
 let t=rasterTree({childEffects:[{type:'NOISE',visible:false}]});await t.figma.ui.onmessage({type:'export',ids:['1']});assert.equal(t.messages.at(-1).type,'pdfs');assert.equal(t.log.copy,undefined);
 t=rasterTree({frameEffects:[{type:'TEXTURE',visible:true}],childEffects:[{type:'GLASS',visible:true}]});await t.figma.ui.onmessage({type:'export',ids:['1']});assert.equal(t.messages.at(-1).type,'pdfs');
});
test('noise cannot fall back to Figma’s own export when no copy can be made',async()=>{const {figma,messages}=rasterTree({cloneFails:true});await figma.ui.onmessage({type:'export',ids:['1']});assert.equal(messages.at(-1).type,'error');assert.match(messages.at(-1).text,/noise or texture in Poster/);});
