const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const PDFLib=require('../vendor/pdf-lib.min.js');
function ui(bundled={}){
 const elements={},clicks=[],blobs=new Map();let nextURL=0;
 const make=tag=>({tag,children:[],value:'',groups:[],options:[],checked:false,
  get isConnected(){return !!this.root||!!(this.parentNode&&this.parentNode.isConnected);},
  remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(child=>child!==this);this.parentNode=null;},
  replaceChildren(...items){for(const child of this.children)child.parentNode=null;this.children=[];this.append(...items);},
  append(...items){for(const item of items){item.parentNode=this;this.children.push(item);if(item.label)this.groups.push(item);else this.options.push(item);}},
  click(){clicks.push({element:this,attached:this.isConnected,filename:this.download,href:this.href});}
 });
 const el=id=>elements[id]||(elements[id]=Object.assign(make('div'),{root:true,checked:id==='auto-size'}));
 const window={},messages=[];
 const context={window,document:{getElementById:el,createElement:make,createTextNode:text=>({textContent:text})},parent:{postMessage:x=>messages.push(x.pluginMessage)},PROFILE_CATALOG:JSON.parse(fs.readFileSync('src/profiles.json')),BUNDLED_PROFILES:bundled,OpenPrintAssets:{decodeProfile:encoded=>Uint8Array.from(atob(encoded),c=>c.charCodeAt(0))},atob,btoa,Uint8Array,DataView,Number,Error,TextEncoder,TextDecoder,Blob,URL:{createObjectURL:blob=>{const url='blob:test-'+(++nextURL);blobs.set(url,blob);return url;},revokeObjectURL:url=>blobs.delete(url)}};
 vm.createContext(context);
 vm.runInContext(fs.readFileSync('vendor/pdf-lib.min.js','utf8'),context);vm.runInContext(fs.readFileSync('src/core.js','utf8'),context);vm.runInContext(fs.readFileSync('src/ui.js','utf8'),context);
 return {window,el,messages,context,clicks,blobs};
}
const frame=(id,width,height)=>({id,name:'Sheet '+id,type:'FRAME',width,height});
test('manual dimensions stay selected when frames change',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});el('width').value='320';el('width').oninput();el('height').value='450';el('height').oninput();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('2',595,842)]}}});assert.equal(el('auto-size').checked,false);assert.equal(el('width').value,'320');assert.equal(el('height').value,'450');});
test('automatic dimensions update when selection changes',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});assert.equal(el('width').value,319.97);await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('2',595,842)]}}});assert.equal(el('width').value,209.9);assert.equal(el('height').value,297.04);});
test('all 15 official profiles are available even without bundled ICC files',()=>{const {el}=ui();assert.equal(el('profile-mode').groups.length,3);assert.equal(el('profile-mode').groups.flatMap(g=>g.options).length,15);});
test('missing preset asks for import and blocks export',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();assert.equal(el('custom-profile').hidden,false);assert.equal(el('export').disabled,true);assert.match(el('status').textContent,/Import/);});
function icc(name){const bytes=Buffer.alloc(156+name.length+1);bytes.writeUInt32BE(bytes.length);bytes.write('CMYK',16);bytes.write('acsp',36);bytes.writeUInt32BE(1,128);bytes.write('desc',132);bytes.writeUInt32BE(144,136);bytes.writeUInt32BE(12+name.length+1,140);bytes.write('desc',144);bytes.writeUInt32BE(name.length+1,152);bytes.write(name,156);return bytes;}
test('named ICC imports are saved and restored with the official name',async()=>{const {window,el,messages}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();const bytes=icc('PSO Coated v3');await el('profile').onchange({target:{files:[{name:'profile.icc',size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}]}});assert.equal(el('custom-profile').hidden,true);assert.equal(el('export').disabled,false);const saved=messages.find(m=>m.type==='save-profile');assert.equal(saved.id,'PSOcoated_v3');const next=ui();next.el('profile-mode').value=saved.id;next.el('profile-mode').onchange();await next.window.onmessage({data:{pluginMessage:{type:'profiles',profiles:{[saved.id]:saved.encoded}}}});assert.equal(next.el('custom-profile').hidden,true);});
test('wrong ICC cannot be imported under a named preset',async()=>{const {el,messages}=ui();el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();const bytes=icc('Different CMYK');await el('profile').onchange({target:{files:[{name:'wrong.icc',size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}]}});assert.match(el('status').textContent,/This file contains Different CMYK/);assert.equal(el('export').disabled,true);assert(!messages.some(m=>m.type==='save-profile'));});
test('storage response arriving during an import does not discard the import',async()=>{const {window,el,messages}=ui();el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();const bytes=icc('PSO Coated v3');let release;const pending=el('profile').onchange({target:{files:[{name:'profile.icc',size:bytes.length,arrayBuffer:()=>new Promise(resolve=>release=resolve)}]}});await window.onmessage({data:{pluginMessage:{type:'profiles',profiles:{}}}});release(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));await pending;assert(messages.some(m=>m.type==='save-profile'));});
test('unit switching converts manual dimensions without accumulating rounding',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});el('width').value='320';el('width').oninput();el('height').value='450';el('height').oninput();for(let i=0;i<5;i++){el('units').value='in';el('units').onchange();assert(Math.abs(Number(el('width').value)-320/25.4)<0.000001);el('units').value='mm';el('units').onchange();assert.equal(Number(el('width').value),320);assert.equal(Number(el('height').value),450);}assert.equal(el('auto-size').checked,false);});
test('inch input exports exact physical dimensions in mm',async()=>{const {window,el,context}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});el('units').value='in';el('units').onchange();el('width').value='8.5';el('width').oninput();el('height').value='11';el('height').oninput();el('export').onclick();const job=vm.runInContext('job',context);assert(Math.abs(job.width-215.9)<1e-10);assert(Math.abs(job.height-279.4)<1e-10);assert.equal(el('units').disabled,true);});
test('automatic and mixed frame sizes keep their physical sizes in inches',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});el('units').value='in';el('units').onchange();assert.equal(el('auto-size').checked,true);assert(Math.abs(Number(el('width').value)-319.97/25.4)<0.000001);await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276),frame('2',595,842)]}}});assert.equal(el('width').value,'');assert.equal(el('width').placeholder,'Varies');});
test('non-frame selection explains why export is blocked',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842),{id:'2',name:'Rectangle',type:'RECTANGLE',width:10,height:10}]}}});assert.equal(el('export').disabled,true);assert.match(el('export-hint').textContent,/Deselect “Rectangle”/);assert.equal(el('frame-count').textContent,'2 selected');});
test('incomplete manual size blocks export until both dimensions are valid',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276),frame('2',595,842)]}}});assert.equal(el('export').disabled,false);el('width').value='320';el('width').oninput();assert.equal(el('export').disabled,true);assert.match(el('export-hint').textContent,/width and height/);el('height').value='5';el('height').oninput();assert.equal(el('export').disabled,true);assert.match(el('export-hint').textContent,/between 10 and 2000/);el('height').value='450';el('height').oninput();assert.equal(el('export').disabled,false);assert.equal(el('export-hint').textContent,'');});

test('export format is shown only for multiple frames and defaults to a multipage PDF',async()=>{const {window,el}=ui();assert.equal(el('export-mode').value,'combined');assert.equal(el('export-options').hidden,true);await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842),frame('2',907,1276)]}}});assert.equal(el('export-options').hidden,false);await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});assert.equal(el('export-options').hidden,true);});
test('individual export snapshots filenames and locks the format while exporting',async()=>{const {window,el,context}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('2',907,1276),frame('1',595,842)]}}});el('export-mode').value='individual';el('export-mode').onchange();el('export').onclick();const current=vm.runInContext('job',context);assert.equal(current.individual,true);assert.deepEqual(Array.from(current.filenames),['Sheet 1.pdf','Sheet 2.pdf']);assert.equal(el('export-mode').disabled,true);await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('3',300,400)]}}});assert.deepEqual(Array.from(current.filenames),['Sheet 1.pdf','Sheet 2.pdf']);});
test('single frames always export one PDF even if individual mode was selected previously',async()=>{const {window,el,context}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});el('export-mode').value='individual';el('export').onclick();assert.equal(vm.runInContext('job.individual',context),false);});
async function convertedPages(){const doc=await PDFLib.PDFDocument.create();for(const size of [[595,842],[907,1276]])doc.addPage(size).drawRectangle({x:12,y:34,width:100,height:50,color:PDFLib.cmyk(.1,.2,.3,.4)});return doc.save();}
async function inspectOutput(bytes,expectedSizes,expectedICC){const result=await PDFLib.PDFDocument.load(bytes);assert.equal(result.getPageCount(),expectedSizes.length);for(let i=0;i<expectedSizes.length;i++){const page=result.getPage(i);assert.equal(page.getWidth(),expectedSizes[i].width*72/25.4);assert.equal(page.getHeight(),expectedSizes[i].height*72/25.4);const text=page.node.Contents().asArray().map(ref=>Buffer.from(PDFLib.decodePDFRawStream(result.context.lookup(ref)).decode()).toString()).join('\n');assert.match(text,/0\.1 0\.2 0\.3 0\.4 k/);assert.match(text,/100/);assert.match(text,/50/);assert(!text.includes(' rg'));}if(expectedICC){const intent=result.catalog.lookup(PDFLib.PDFName.of('OutputIntents'),PDFLib.PDFArray).lookup(0,PDFLib.PDFDict);const embedded=intent.lookup(PDFLib.PDFName.of('DestOutputProfile'),PDFLib.PDFRawStream);assert.equal(embedded.dict.lookup(PDFLib.PDFName.of('N'),PDFLib.PDFNumber).asNumber(),4);assert.deepEqual(Buffer.from(PDFLib.decodePDFRawStream(embedded).decode()),expectedICC);}else assert.equal(result.catalog.get(PDFLib.PDFName.of('OutputIntents')),undefined);}
function exportFixture(){return {individual:true,filename:'Sheet 1.pdf',filenames:['Sheet 1.pdf','Sheet 2.pdf'],width:null,height:null,auto:true,sizes:[{width:209.9,height:297.04},{width:319.97,height:450.14}],icc:fs.readFileSync('vendor/profiles/CoatedFOGRA39.icc'),name:'Coated FOGRA39 (ISO 12647-2:2004)'};}
test('individual PDFs retain vectors, exact embedded ICC and each frame’s automatic size',async()=>{const {context}=ui(),current=exportFixture();const downloads=await context.prepareDownloads(await convertedPages(),current);assert.deepEqual(Array.from(downloads,d=>d.filename),current.filenames);for(let i=0;i<downloads.length;i++)await inspectOutput(downloads[i].bytes,[current.sizes[i]],current.icc);});
test('individual PDFs apply a manual print size to every file without a profile',async()=>{const {context}=ui(),current={...exportFixture(),auto:false,sizes:null,width:320,height:450,icc:null,name:''};const downloads=await context.prepareDownloads(await convertedPages(),current);assert.equal(downloads.length,2);for(const output of downloads)await inspectOutput(output.bytes,[{width:320,height:450}],null);});
test('combined format keeps both pages in one PDF with the first frame filename',async()=>{const {context}=ui(),current={...exportFixture(),individual:false};const downloads=await context.prepareDownloads(await convertedPages(),current);assert.equal(downloads.length,1);assert.equal(downloads[0].filename,'Sheet 1.pdf');await inspectOutput(downloads[0].bytes,current.sizes,current.icc);});
test('individual exports reject a converted PDF with a different frame count',async()=>{const {context}=ui(),current=exportFixture();current.filenames.push('Sheet 3.pdf');const bytes=await convertedPages();await assert.rejects(()=>context.prepareDownloads(bytes,current),/count|match/i);});

const sampleDownloads=()=>[{filename:'Álvaro name tag.pdf',bytes:new Uint8Array([37,80,68,70,1])},{filename:'Sheet 2.pdf',bytes:new Uint8Array([37,80,68,70,2])}];
const anchors=node=>[...(node.tag==='a'?[node]:[]),...(node.children||[]).flatMap(anchors)];
test('individual PDF delivery provides attached links with original filenames and no automatic download loop',async()=>{
 const {context,el,clicks,blobs}=ui(),outputs=sampleDownloads();context.showDownloads(outputs);
 assert.equal(clicks.length,0);
 const links=anchors(el('status'));assert.equal(links.length,outputs.length);
 for(let i=0;i<outputs.length;i++){
  assert.equal(links[i].download,outputs[i].filename);assert.equal(links[i].isConnected,true);
  const blob=blobs.get(links[i].href);assert.equal(blob.type,'application/pdf');
  assert.deepEqual(Buffer.from(await blob.arrayBuffer()),Buffer.from(outputs[i].bytes));
  links[i].click();
 }
 assert.equal(clicks.length,2);assert(clicks.every(click=>click.attached));assert.deepEqual(clicks.map(click=>click.filename),outputs.map(output=>output.filename));
 assert(!String(el('status').textContent||'').includes('Export complete'));
});
test('duplicate frame names keep separate PDF links and unchanged bytes',async()=>{
 const {context,el,clicks,blobs}=ui(),outputs=sampleDownloads();outputs[1].filename=outputs[0].filename;context.showDownloads(outputs);
 assert.equal(clicks.length,0);
 const links=anchors(el('status'));assert.equal(links.length,2);assert.notEqual(links[0].href,links[1].href);
 for(let i=0;i<links.length;i++){
  assert.equal(links[i].download,outputs[i].filename);assert.equal(links[i].isConnected,true);
  assert.deepEqual(Buffer.from(await blobs.get(links[i].href).arrayBuffer()),Buffer.from(outputs[i].bytes));
 }
});
test('single PDF delivery mounts its original filename link before its only automatic click',async()=>{
 const {context,clicks,blobs}=ui(),output=sampleDownloads()[0];context.showDownloads([output]);
 assert.equal(clicks.length,1);assert.equal(clicks[0].attached,true);assert.equal(clicks[0].filename,output.filename);
 const blob=blobs.get(clicks[0].href);assert.equal(blob.type,'application/pdf');assert.deepEqual(Buffer.from(await blob.arrayBuffer()),Buffer.from(output.bytes));
});
