const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function ui(bundled={}){const elements={};const make=()=>({value:'',groups:[],options:[],checked:false,remove(){},replaceChildren(){},append(item){if(item.label)this.groups.push(item);else this.options.push(item);}});const el=id=>elements[id]||(elements[id]={...make(),checked:id==='auto-size'});const window={};const messages=[];const context={window,document:{getElementById:el,createElement:make},parent:{postMessage:x=>messages.push(x.pluginMessage)},PROFILE_CATALOG:JSON.parse(fs.readFileSync('src/profiles.json')),BUNDLED_PROFILES:bundled,atob,btoa,Uint8Array,DataView,Number,Error};vm.createContext(context);vm.runInContext(fs.readFileSync('src/core.js','utf8'),context);vm.runInContext(fs.readFileSync('src/ui.js','utf8'),context);return {window,el,messages,context};}
const frame=(id,width,height)=>({id,name:'Sheet '+id,type:'FRAME',width,height});
test('manual dimensions stay selected when frames change',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});el('width').value='320';el('width').oninput();el('height').value='450';el('height').oninput();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('2',595,842)]}}});assert.equal(el('auto-size').checked,false);assert.equal(el('width').value,'320');assert.equal(el('height').value,'450');});
test('automatic dimensions update when selection changes',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});assert.equal(el('width').value,319.97);await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('2',595,842)]}}});assert.equal(el('width').value,209.9);assert.equal(el('height').value,297.04);});
test('all 15 official profiles are available even without bundled ICC files',()=>{const {el}=ui();assert.equal(el('profile-mode').groups.length,3);assert.equal(el('profile-mode').groups.flatMap(g=>g.options).length,15);});
test('missing preset asks for import and blocks export',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();assert.equal(el('custom-profile').hidden,false);assert.equal(el('export').disabled,true);assert.match(el('status').textContent,/Import/);});
function icc(name){const bytes=Buffer.alloc(156+name.length+1);bytes.writeUInt32BE(bytes.length);bytes.write('CMYK',16);bytes.write('acsp',36);bytes.writeUInt32BE(1,128);bytes.write('desc',132);bytes.writeUInt32BE(144,136);bytes.writeUInt32BE(12+name.length+1,140);bytes.write('desc',144);bytes.writeUInt32BE(name.length+1,152);bytes.write(name,156);return bytes;}
test('named ICC imports are saved and restored with the official name',async()=>{const {window,el,messages}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();const bytes=icc('PSO Coated v3');await el('profile').onchange({target:{files:[{name:'profile.icc',size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}]}});assert.equal(el('custom-profile').hidden,true);assert.equal(el('export').disabled,false);const saved=messages.find(m=>m.type==='save-profile');assert.equal(saved.id,'PSOcoated_v3');const next=ui();next.el('profile-mode').value=saved.id;next.el('profile-mode').onchange();await next.window.onmessage({data:{pluginMessage:{type:'profiles',profiles:{[saved.id]:saved.encoded}}}});assert.equal(next.el('custom-profile').hidden,true);});
test('wrong ICC cannot be imported under a named preset',async()=>{const {el,messages}=ui();el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();const bytes=icc('Different CMYK');await el('profile').onchange({target:{files:[{name:'wrong.icc',size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}]}});assert.match(el('status').textContent,/This file contains Different CMYK/);assert.equal(el('export').disabled,true);assert(!messages.some(m=>m.type==='save-profile'));});
test('storage response arriving during an import does not discard the import',async()=>{const {window,el,messages}=ui();el('profile-mode').value='PSOcoated_v3';el('profile-mode').onchange();const bytes=icc('PSO Coated v3');let release;const pending=el('profile').onchange({target:{files:[{name:'profile.icc',size:bytes.length,arrayBuffer:()=>new Promise(resolve=>release=resolve)}]}});await window.onmessage({data:{pluginMessage:{type:'profiles',profiles:{}}}});release(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));await pending;assert(messages.some(m=>m.type==='save-profile'));});
test('unit switching converts manual dimensions without accumulating rounding',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});el('width').value='320';el('width').oninput();el('height').value='450';el('height').oninput();for(let i=0;i<5;i++){el('units').value='in';el('units').onchange();assert(Math.abs(Number(el('width').value)-320/25.4)<0.000001);el('units').value='mm';el('units').onchange();assert.equal(Number(el('width').value),320);assert.equal(Number(el('height').value),450);}assert.equal(el('auto-size').checked,false);});
test('inch input exports exact physical dimensions in mm',async()=>{const {window,el,context}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',595,842)]}}});el('units').value='in';el('units').onchange();el('width').value='8.5';el('width').oninput();el('height').value='11';el('height').oninput();el('export').onclick();const job=vm.runInContext('job',context);assert(Math.abs(job.width-215.9)<1e-10);assert(Math.abs(job.height-279.4)<1e-10);assert.equal(el('units').disabled,true);});
test('automatic and mixed frame sizes keep their physical sizes in inches',async()=>{const {window,el}=ui();await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276)]}}});el('units').value='in';el('units').onchange();assert.equal(el('auto-size').checked,true);assert(Math.abs(Number(el('width').value)-319.97/25.4)<0.000001);await window.onmessage({data:{pluginMessage:{type:'selection',frames:[frame('1',907,1276),frame('2',595,842)]}}});assert.equal(el('width').value,'');assert.equal(el('width').placeholder,'Varies');});
